/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UsuarioController;
import DTO.UsuarioDTO;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;

import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author JETTSUSHD
 */
public class LoginView extends javax.swing.JFrame {

    private UsuarioController usuarioController = null;

    /**
     * Creates new form LoginView
     */
    public LoginView() {

        usuarioController = new UsuarioController();
        initComponents();
        setLocationRelativeTo(null);
        agregarJavaHelp();
        
        setTitle("Ventana login");
        setResizable(false);
        keyBinding();
    }
    
     public void keyBinding() {
        // Acción para aplicar los filtros cuando se presiona ENTER
        Action login = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                bInicio.doClick(); // Simula un click en aplicar filtro
            }
        };

        // Añadir keybinding para la tecla ENTER para aplicar los filtros
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "LOGIN");
        rootPane.getActionMap().put("LOGIN", login); // Fixed: rootpane -> rootPane

        requestFocusInWindow();
        setFocusable(true);
    }

    private void agregarJavaHelp() {
        try {
            URL hsURL = getClass().getClassLoader().getResource("help/help_set.hs");

            HelpSet helpset = new HelpSet(null, hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpKey(this.getContentPane(), "MainView2", helpset);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lCorreo = new javax.swing.JLabel();
        lContrasena = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        bInicio = new javax.swing.JButton();
        passfieldContra = new javax.swing.JPasswordField();
        chkMostrarContrasena = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lCorreo.setText("Correo:");
        lCorreo.setPreferredSize(new java.awt.Dimension(100, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 0, 10);
        getContentPane().add(lCorreo, gridBagConstraints);

        lContrasena.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lContrasena.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 16, 0, 10);
        getContentPane().add(lContrasena, gridBagConstraints);

        tfCorreo.setPreferredSize(new java.awt.Dimension(400, 44));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 17);
        getContentPane().add(tfCorreo, gridBagConstraints);

        bInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bInicio.setText("Iniciar sesión");
        bInicio.setPreferredSize(new java.awt.Dimension(200, 44));
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 17, 17);
        getContentPane().add(bInicio, gridBagConstraints);

        passfieldContra.setMinimumSize(new java.awt.Dimension(150, 22));
        passfieldContra.setPreferredSize(new java.awt.Dimension(400, 44));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 17);
        getContentPane().add(passfieldContra, gridBagConstraints);

        chkMostrarContrasena.setText("Mostrar contraseña");
        chkMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarContrasenaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 9, 0, 17);
        getContentPane().add(chkMostrarContrasena, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        String correo = tfCorreo.getText();
        String contraseña = new String(passfieldContra.getPassword()); // Obtener contraseña de JPasswordField

        // Validar que los campos no estén vacíos
        if (correo.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener el resultado de la autenticación del controller
        String resultado = usuarioController.autenticarUsuario(correo, contraseña);

        if ("Inicio de sesión exitoso.".equals(resultado)) {
            // Si la autenticación es exitosa, obtenemos el usuario por correo
            UsuarioDTO usuario = usuarioController.obtenerUsuarioPorCorreo(correo);
            if (usuario != null) {
                JOptionPane.showMessageDialog(this, "✅ Bienvenido, " + usuario.getNombre(), "Inicio de Sesión Exitoso", JOptionPane.INFORMATION_MESSAGE);
                abrirVentanaPrincipal(usuario);
            }
        } else {
            JOptionPane.showMessageDialog(this, "❌ " + resultado, "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
            tfCorreo.setText("");
            passfieldContra.setText("");
        }
    }//GEN-LAST:event_bInicioActionPerformed

    private void chkMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarContrasenaActionPerformed
        // TODO add your handling code here:
        mostrarContra();
    }//GEN-LAST:event_chkMostrarContrasenaActionPerformed

    // Método para cambiar la visibilidad de la contraseña
    private void mostrarContra() {
        if (chkMostrarContrasena.isSelected()) {
            passfieldContra.setEchoChar((char) 0); // Mostrar texto 
        } else {
            passfieldContra.setEchoChar('•'); // Ocultar con puntos
        }
    }

    // Changed parameter type from Usuario to UsuarioDTO
    private void abrirVentanaPrincipal(UsuarioDTO usuario) {
        JOptionPane.showMessageDialog(this, "🔓 Acceso permitido para: " + usuario.getTipoUsuario(), "Información", JOptionPane.INFORMATION_MESSAGE);
        MainView2 mainView = new MainView2(usuario);
        mainView.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInicio;
    private javax.swing.JCheckBox chkMostrarContrasena;
    private javax.swing.JLabel lContrasena;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JPasswordField passfieldContra;
    private javax.swing.JTextField tfCorreo;
    // End of variables declaration//GEN-END:variables
}
