/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Modelos.Usuario;
import Service.VentaService;
import Controller.UsuarioController;
import DTO.UsuarioDTO;
import java.awt.event.ActionEvent;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author JETTSUSHD
 */
public class MainView2 extends javax.swing.JFrame {

    private UsuarioDTO usuario;

    private HelpSet helpSet;
    private HelpBroker helpBroker;

    /**
     * Creates new form MainView2
     */
    public MainView2(UsuarioDTO usuario) {
        this.usuario = usuario;

        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

        setTitle("Gestión de Ventas - Bienvenido, " + usuario.getNombre());
        lBienvenida.setText("Bienvenido, " + usuario.getNombre() + " | Rol: " + usuario.getTipoUsuario());
        // RESTRINGIR ACCESO A GESTIÓN DE USUARIOS SI NO ES ADMIN
        if (!usuario.getTipoUsuario().equalsIgnoreCase("admin")) {
            bUsuarios.setVisible(false);
            //bUsuarios.setEnabled(false); // Otra opcion Deshabilitar
        }

        initHelp();
        ejecutarF1();
        
        setResizable(false);
        // Evitar que la "X" cierre toda la aplicación
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        // Capturar evento al cerrar la ventana con "X"
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrarSesion();
            }
        });
    }

    private void initHelp() {
        try {
            // Obtener el recurso desde el classpath
            ClassLoader cl = this.getClass().getClassLoader();
            URL hsURL = cl.getResource("help/help_set.hs");

            if (hsURL == null) {
                System.out.println("No se encontró el archivo de ayuda en el classpath.");
                return;
            }

            System.out.println("Archivo de ayuda encontrado en: " + hsURL);

            // Cargar el HelpSet
            helpSet = new HelpSet(cl, hsURL);
            helpBroker = helpSet.createHelpBroker();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ejecutarF1() {
        KeyStroke f1KeyStroke = KeyStroke.getKeyStroke("F1");
        Action helpAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                miAyudaActionPerformed(null); // Ejecuta el mismo evento del botón
            }
        };

        // Asignar la acción al panel principal (ventana) para que funcione en cualquier parte
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f1KeyStroke, "help");
        this.getRootPane().getActionMap().put("help", helpAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pBienvenida = new javax.swing.JPanel();
        lBienvenida = new javax.swing.JLabel();
        pCentral = new javax.swing.JPanel();
        bProductos = new javax.swing.JButton();
        bUsuarios = new javax.swing.JButton();
        bVentas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miCerrarSesion = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        miAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pBienvenida.setLayout(new java.awt.GridBagLayout());

        lBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lBienvenida.setText("Bienvenido ");
        pBienvenida.add(lBienvenida, new java.awt.GridBagConstraints());

        getContentPane().add(pBienvenida, java.awt.BorderLayout.PAGE_START);

        pCentral.setLayout(new java.awt.GridBagLayout());

        bProductos.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bProductos.setLabel("Gestión de productos");
        bProductos.setPreferredSize(new java.awt.Dimension(700, 71));
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 0, 14);
        pCentral.add(bProductos, gridBagConstraints);

        bUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bUsuarios.setText("Gestión de usuarios");
        bUsuarios.setPreferredSize(new java.awt.Dimension(700, 71));
        bUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 14, 14);
        pCentral.add(bUsuarios, gridBagConstraints);

        bVentas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bVentas.setText("Gestión de ventas");
        bVentas.setPreferredSize(new java.awt.Dimension(700, 71));
        bVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 0, 14);
        pCentral.add(bVentas, gridBagConstraints);

        getContentPane().add(pCentral, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        mArchivo.setText("Archivo");
        mArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miCerrarSesion.setText("Cerrar sesión");
        miCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarSesionActionPerformed(evt);
            }
        });
        mArchivo.add(miCerrarSesion);

        jMenuBar1.add(mArchivo);

        mAyuda.setText("Ayuda");
        mAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miAyuda.setText("Acerca de");
        miAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAyudaActionPerformed(evt);
            }
        });
        mAyuda.add(miAyuda);

        jMenuBar1.add(mAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarSesionActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            new LoginView().setVisible(true);
        }
    }//GEN-LAST:event_miCerrarSesionActionPerformed

    private void bVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentasActionPerformed
        // TODO add your handling code here:
        GestionVentas ventas = new GestionVentas(usuario);
        ventas.setVisible(true);
        dispose();
    }//GEN-LAST:event_bVentasActionPerformed

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        // TODO add your handling code here:
        ProductoView productos = new ProductoView(usuario);
        productos.setVisible(true);
        dispose();
    }//GEN-LAST:event_bProductosActionPerformed

    private void bUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsuariosActionPerformed
        // TODO add your handling code here:
        GestionUsuario2 usuarios = new GestionUsuario2(usuario); 
        usuarios.setVisible(true);

        dispose();
    }//GEN-LAST:event_bUsuariosActionPerformed

    private void miAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAyudaActionPerformed
        // TODO add your handling code here:
        if (helpBroker != null) {
            helpBroker.setDisplayed(true);
        } else {
            System.out.println("El sistema de ayuda no está disponible.");
        }
    }//GEN-LAST:event_miAyudaActionPerformed

    private void cerrarSesion() {
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas cerrar sesión?", "Cerrar Sesión",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dispose(); // Cierra solo esta ventana

            // Asegurar que la nueva ventana se abre correctamente en la EDT
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginView().setVisible(true);
                }
            });
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bProductos;
    private javax.swing.JButton bUsuarios;
    private javax.swing.JButton bVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuItem miAyuda;
    private javax.swing.JMenuItem miCerrarSesion;
    private javax.swing.JPanel pBienvenida;
    private javax.swing.JPanel pCentral;
    // End of variables declaration//GEN-END:variables
}
